#!/bin/bash

OE_BRAND="Manzada"
OE_WEB="manzada"
OE_HOME="/home/odoo/odoo-server/"

echo "stopping odoo-server..."
sudo systemctl stop odoo-server

echo "Removing failed debranding..."
sudo rm -rf /home/odoo/odoo-server

echo "Rollback..."
sudo cp -r /home/odoo/master-server /home/odoo/odoo-server

# Hide specific menu in user menu
echo "Customize Usermenu ..."
sudo sed -i '/id: "documentation",/a hide: "true",' /home/odoo/odoo-server/addons/web/static/src/webclient/user_menu/user_menu_items.js
sudo sed -i '/id: "support",/a hide: "true",' /home/odoo/odoo-server/addons/web/static/src/webclient/user_menu/user_menu_items.js
sudo sed -i '/id: "settings",/a hide: "true",' /home/odoo/odoo-server/addons/web/static/src/webclient/user_menu/user_menu_items.js
sudo sed -i '/id: "account",/a hide: "true",' /home/odoo/odoo-server/addons/web/static/src/webclient/user_menu/user_menu_items.js


echo "Text debranding ..."
files=$(sudo grep -rl "Odoo" $OE_HOME) && echo $files | sudo xargs sed -i 's/\bOdoo\b/Manzada/g'
files=$(sudo grep -rl 'www.odoo.com' $OE_HOME) && echo $files | sudo xargs sed -i 's/www.odoo.com/www.manzada.net/g'
files=$(sudo grep -rl 'odoo.com' $OE_HOME) && echo $files | sudo xargs sed -i 's/odoo.com/manzada.net/g'



sed -i '/id: "documentation",/a hide: "true",' /usr/lib/python3/dist-packages/odoo/addons/web/static/src/webclient/user_menu/user_menu_items.js
sed -i '/id: "support",/a hide: "true",' /usr/lib/python3/dist-packages/odoo/addons/web/static/src/webclient/user_menu/user_menu_items.js
sed -i '/id: "settings",/a hide: "true",' /usr/lib/python3/dist-packages/odoo/addons/web/static/src/webclient/user_menu/user_menu_items.js
sed -i '/id: "account",/a hide: "true",' /usr/lib/python3/dist-packages/odoo/addons/web/static/src/webclient/user_menu/user_menu_items.js


files=$(grep -rl --exclude="Read*" --exclude-dir="/usr/lib/python3/dist-packages/odoo/addons/web/static/img" "Odoo" "/usr/lib/python3/dist-packages/odoo/" | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/\bOdoo\b/MERP/g'
files=$(grep -rl --exclude="Read*" --exclude-dir="/usr/lib/python3/dist-packages/odoo/addons/web/static/img" 'www.odoo.com' "/usr/lib/python3/dist-packages/odoo/" | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/www.odoo.com/www.manzada.net/g'
files=$(grep -rl --exclude="Read*" --exclude-dir="/usr/lib/python3/dist-packages/odoo/addons/web/static/img" 'odoo.com' "/usr/lib/python3/dist-packages/odoo/" | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/accounts.odoo.com/accounts.manzada.net/g'
files=$(grep -rl --exclude="Read*" --exclude-dir="/usr/lib/python3/dist-packages/odoo/addons/web/static/img" 'Negara-Negara' "/usr/lib/python3/dist-packages/odoo/" | cut -f 1 -d ':' | sort | uniq) && echo $files | xargs sed -i 's/Negara-Negara/Negara/g'

files=$(grep -rl oldstr path | cut -f 1 -d ':' | sort | uniq)

#files=$(sudo grep -rl 'www.odoo.com' /home/odoo/odoo-server/odoo/addons/base/) && echo $files | sudo xargs sed -i 's/www.odoo.com/www.manzada.net/g'
#files=$(sudo grep -rl 'odoo.com' /home/odoo/odoo-server/odoo/addons/base/) && echo $files | sudo xargs sed -i 's/odoo.com/manzada.net/g'

#files=$(sudo grep -rl "Odoo" $OE_HOME) && echo $files | sudo xargs sed -i '/"/s/Odoo/$OE_BRAND/g'
#files=$(sudo grep -rl "Odoo" $OE_HOME) && echo $files | sudo xargs sed -i "/'/s/Odoo/$OE_BRAND/g"
#files=$(sudo grep -rl "odoo" $OE_HOME) && echo $files | sudo xargs sed -i '/"/s/odoo/$OE_WEB/g'
#files=$(sudo grep -rl "odoo" $OE_HOME) && echo $files | sudo xargs sed -i "/'/s/odoo/$OE_WEB/g"
#files=$(sudo grep -rl ">Odoo<" $OE_HOME) && echo $files | sudo xargs sed -i 's/>Odoo</>$OE_BRAND</g'

#files=$(sudo grep -rl 'www.odoo.com' /home/odoo/odoo-server/) && echo $files | sudo xargs sed -i 's/www.odoo.com/manzada.net/g'
#files=$(sudo grep -rl 'odoo.com' /home/odoo/odoo-server/) && echo $files | sudo xargs sed -i 's/odoo.com/manzada.net/g'
#files=$(sudo grep -rl ' Odoo ' /home/odoo/odoo-server/) && echo $files | sudo xargs sed -i 's/ Odoo / Manzada /g'
#files=$(sudo grep -rl 'Odoo ' /home/odoo/odoo-server/) && echo $files | sudo xargs sed -i 's/Odoo /Manzada /g'
#files=$(sudo grep -rl '>Odoo<' /home/odoo/odoo-server/) && echo $files | sudo xargs sed -i 's/>Odoo</>Manzada</g'
#files=$(sudo grep -rl "'Odoo'" /home/odoo/odoo-server/) && echo $files | sudo xargs sed -i "s/'Odoo'/'Manzada'/g"
#files=$(sudo grep -rl '"Odoo"' /home/odoo/odoo-server/) && echo $files | sudo xargs sed -i 's/"Odoo"/"Manzada"/g'
#files=$(sudo grep -rl 'Odoo!' /home/odoo/odoo-server/) && echo $files | sudo xargs sed -i 's/Odoo!/Manzada!/g'
#files=$(sudo grep -rl ' Odoo.' /home/odoo/odoo-server/) && echo $files | sudo xargs sed -i 's/ Odoo./ Manzada./g'
#files=$(sudo grep -rl ' Odoo,' /home/odoo/odoo-server/) && echo $files | sudo xargs sed -i 's/ Odoo,/ Manzada,/g'
#files=$(sudo grep -rl "'OdooBot'" /home/odoo/odoo-server/) && echo $files | sudo xargs sed -i "s/'OdooBot'/'Ramdan'/g"
#files=$(sudo grep -rl '"OdooBot"' /home/odoo/odoo-server/) && echo $files | sudo xargs sed -i 's/"OdooBot"/"Ramdan"/g'

echo "Icon debranding ..."
yes | sudo cp *.png /home/odoo/odoo-server/addons/web/static/img/
yes | sudo cp *.svg /home/odoo/odoo-server/addons/web/static/img/
yes | sudo cp *.ico /home/odoo/odoo-server/addons/web/static/img/

echo "Starting Odoo-server..."
sudo systemctl start odoo-server
